import './assets/corpovideo.css';
import './assets/desc.css';
import Comentarios from './Comentarios';

function Video ()
{
    return <div className='Video'>
        <div className='Video-local'>
            <div id='vid'></div>
            <div id='controles'>
                <div>
                <button>▶</button>
                <button>❚❚</button>
                <button>◀</button>
                <button>🕪</button>
                <p>10:10/20:20</p>
                </div>
                <div>
                <button>🖵</button>
                <button>⚙</button>
                <button>⛶</button>
                </div>
            </div>
            <div id='barra'></div>
            <div id='barraNormal'></div>
        </div>
        <div className='Video-descs'>
            <div className='desc-principal'>
                <h2>Changing Seasons -Reload-</h2>
                <div className='canal'>
                    <img src="https://yt3.googleusercontent.com/7yozwNYFCC7GE2ZqEzxjSiqvUb1PVXrm3BhBsEMga2FYzr0BLhTvN5bk-NGeB_13OJFHmtGR=s160-c-k-c0x00ffffff-no-rj" alt="img"/>
                    <div>
                     <h4>Azumi Takahashi - Tema</h4>
                     <p>42,3 mil inscritos</p>
                    </div>
                    <button id='inscrever'>Inscrever-se</button>
                </div>
                <div className='curtir'>
                    <button className='curtir-b'>❤ 26 mil</button>
                    <button className='curtir-b sqr'>↺  </button>
                    <button className='curtir-b'>➦  Compartilhar</button>
                    <button className='curtir-b sqr'>...</button>
                </div>
            </div>
            <div className='desc-secundaria'>
                <p>3.072.456 visualizações  23 de abr. de 2024</p>
                <p>Provided to YouTube by NexTone Inc.</p>
                <p>Changing Seasons Reload · Azumi Takahashi · ATLUS Sound Team · ATLUS GAME MUSIC · アトラス · 目黒将司 · ATLUS Sound Team</p>
                <p>Persona 3 Reload Original Soundtrack</p>
                <p>Released on: 2024-04-24</p>
                <p>Auto-generated by YouTube.</p>       
                <p><strong>Mostrar Menos</strong></p>       
            </div>
        </div>
        <Comentarios/>
        


    </div>
}
export default Video;